::need to fast backup all cloned strings to bakforcloned folder when need to reclone updated english strings 
if not exist bakforcloned md bakforcloned 
move BeeingFemale_CHINESE.DLSTRINGS bakforcloned\ 
move BeeingFemale_CZECH.DLSTRINGS bakforcloned\ 
move BeeingFemale_DANISH.DLSTRINGS bakforcloned\ 
move BeeingFemale_FINNISH.DLSTRINGS bakforcloned\ 
move BeeingFemale_FRENCH.DLSTRINGS bakforcloned\ 
move BeeingFemale_GERMAN.DLSTRINGS bakforcloned\ 
move BeeingFemale_ITALIAN.DLSTRINGS bakforcloned\ 
move BeeingFemale_JAPANESE.DLSTRINGS bakforcloned\ 
move BeeingFemale_POLISH.DLSTRINGS bakforcloned\ 
move BeeingFemale_SPANISH.DLSTRINGS bakforcloned\ 
move BeeingFemale_SWEDISH.DLSTRINGS bakforcloned\ 
move BeeingFemale_TURKISH.DLSTRINGS bakforcloned\ 
move BeeingFemale_ARABIC.DLSTRINGS bakforcloned\ 
move BeeingFemale_GREEK.DLSTRINGS bakforcloned\ 
move BeeingFemale_HUNGARIAN.DLSTRINGS bakforcloned\ 
move BeeingFemale_NORWEGIAN.DLSTRINGS bakforcloned\ 
move BeeingFemale_PORTUGUESE.DLSTRINGS bakforcloned\ 
move BeeingFemale_CHINESE.ILSTRINGS bakforcloned\ 
move BeeingFemale_CZECH.ILSTRINGS bakforcloned\ 
move BeeingFemale_DANISH.ILSTRINGS bakforcloned\ 
move BeeingFemale_FINNISH.ILSTRINGS bakforcloned\ 
move BeeingFemale_FRENCH.ILSTRINGS bakforcloned\ 
move BeeingFemale_GERMAN.ILSTRINGS bakforcloned\ 
move BeeingFemale_ITALIAN.ILSTRINGS bakforcloned\ 
move BeeingFemale_JAPANESE.ILSTRINGS bakforcloned\ 
move BeeingFemale_POLISH.ILSTRINGS bakforcloned\ 
move BeeingFemale_SPANISH.ILSTRINGS bakforcloned\ 
move BeeingFemale_SWEDISH.ILSTRINGS bakforcloned\ 
move BeeingFemale_TURKISH.ILSTRINGS bakforcloned\ 
move BeeingFemale_ARABIC.ILSTRINGS bakforcloned\ 
move BeeingFemale_GREEK.ILSTRINGS bakforcloned\ 
move BeeingFemale_HUNGARIAN.ILSTRINGS bakforcloned\ 
move BeeingFemale_NORWEGIAN.ILSTRINGS bakforcloned\ 
move BeeingFemale_PORTUGUESE.ILSTRINGS bakforcloned\ 
move BeeingFemale_CHINESE.STRINGS bakforcloned\ 
move BeeingFemale_CZECH.STRINGS bakforcloned\ 
move BeeingFemale_DANISH.STRINGS bakforcloned\ 
move BeeingFemale_FINNISH.STRINGS bakforcloned\ 
move BeeingFemale_FRENCH.STRINGS bakforcloned\ 
move BeeingFemale_GERMAN.STRINGS bakforcloned\ 
move BeeingFemale_ITALIAN.STRINGS bakforcloned\ 
move BeeingFemale_JAPANESE.STRINGS bakforcloned\ 
move BeeingFemale_POLISH.STRINGS bakforcloned\ 
move BeeingFemale_SPANISH.STRINGS bakforcloned\ 
move BeeingFemale_SWEDISH.STRINGS bakforcloned\ 
move BeeingFemale_TURKISH.STRINGS bakforcloned\ 
move BeeingFemale_ARABIC.STRINGS bakforcloned\ 
move BeeingFemale_GREEK.STRINGS bakforcloned\ 
move BeeingFemale_HUNGARIAN.STRINGS bakforcloned\ 
move BeeingFemale_NORWEGIAN.STRINGS bakforcloned\ 
move BeeingFemale_PORTUGUESE.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_CHINESE.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_CZECH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_DANISH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_FINNISH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_FRENCH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_GERMAN.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_ITALIAN.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_JAPANESE.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_POLISH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_SPANISH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_SWEDISH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_TURKISH.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_ARABIC.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_GREEK.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_HUNGARIAN.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_NORWEGIAN.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_PORTUGUESE.DLSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_CHINESE.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_CZECH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_DANISH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_FINNISH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_FRENCH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_GERMAN.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_ITALIAN.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_JAPANESE.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_POLISH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_SPANISH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_SWEDISH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_TURKISH.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_ARABIC.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_GREEK.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_HUNGARIAN.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_NORWEGIAN.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_PORTUGUESE.ILSTRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_CHINESE.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_CZECH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_DANISH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_FINNISH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_FRENCH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_GERMAN.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_ITALIAN.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_JAPANESE.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_POLISH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_SPANISH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_SWEDISH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_TURKISH.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_ARABIC.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_GREEK.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_HUNGARIAN.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_NORWEGIAN.STRINGS bakforcloned\ 
move BeeingFemaleBasicAddOn_PORTUGUESE.STRINGS bakforcloned\ 
del _BakClonedFromEnglish.bat 
